# Generated by Django 5.2.8 on 2025-11-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_farmerfollow"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bank_name",
            field=models.CharField(
                blank=True, help_text="e.g. CBE, Awash", max_length=50
            ),
        ),
    ]
