# Generated by Django 5.2.8 on 2025-12-01 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_bank_account_number_customuser_bank_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workforce_type",
                    models.CharField(
                        choices=[
                            ("CDN", "CDN - Independent Contractor"),
                            ("DEDICATED", "Dedicated Fleet - Employee"),
                        ],
                        default="CDN",
                        max_length=20,
                    ),
                ),
                (
                    "national_id_image",
                    models.ImageField(
                        blank=True,
                        help_text="National ID (Kebele ID) Front",
                        null=True,
                        upload_to="driver_documents/ids/",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "license_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="driver_documents/licenses/"
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        help_text="e.g. Isuzu FSR, Toyota Van", max_length=50
                    ),
                ),
                ("max_capacity_kg", models.IntegerField(default=100)),
                (
                    "reliability_score",
                    models.DecimalField(decimal_places=2, default=3.0, max_digits=3),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved & Active"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
