# Generated by Django 5.2.8 on 2025-12-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_driverprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="DedicatedEmployee",
            fields=[],
            options={
                "verbose_name": "👨\u200d✈️ Dedicated Employee",
                "verbose_name_plural": "👨\u200d✈️ Dedicated Fleet (Employees)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.customuser",),
        ),
    ]
