# Generated by Django 5.2.8 on 2025-12-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_dedicatedemployee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farmerfollow",
            options={
                "verbose_name": "⭐ Farmer Follow",
                "verbose_name_plural": "⭐ Farmer Follows",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                help_text="Primary identifier for login", max_length=15, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="national_id_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="driver_documents/ids/"
            ),
        ),
    ]
