# Generated by Django 5.2.8 on 2025-11-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price_per_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_quantity", models.IntegerField(help_text="Quantity in KG")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="crop_images/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
