# Generated by Django 5.2.8 on 2025-11-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_groupbuy_groupmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="location",
            field=models.CharField(
                default="Farm Location",
                help_text="e.g. Sebeta, Kebele 04",
                max_length=100,
            ),
        ),
    ]
