# Generated by Django 5.2.8 on 2025-11-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0006_crop_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash on Delivery"),
                    ("telebirr", "Telebirr"),
                    ("bank", "Mobile Banking"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_proof",
            field=models.ImageField(blank=True, null=True, upload_to="payment_proofs/"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("payment_review", "Payment Verification Needed"),
                    ("pending", "Pending Delivery"),
                    ("assigned", "Driver Assigned"),
                    ("picked_up", "Picked Up"),
                    ("delivered", "Delivered"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
