# Generated by Django 5.2.8 on 2025-11-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0007_order_payment_method_order_payment_proof_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="order_snapshots/"
            ),
        ),
    ]
