# Generated by Django 5.2.8 on 2025-11-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_order_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="driver_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the person delivering",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="driver_phone",
            field=models.CharField(
                blank=True, help_text="Phone of the driver", max_length=20, null=True
            ),
        ),
    ]
