# Generated by Django 5.2.8 on 2025-11-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0010_order_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupbuy",
            name="delivery_location",
            field=models.CharField(
                default="Unknown Location",
                help_text="Where will members collect their share?",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
