# Generated by Django 5.2.8 on 2025-11-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0011_groupbuy_delivery_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="commission_fee",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="5% Platform Fee", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="seller_earnings",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount the seller actually gets",
                max_digits=12,
            ),
        ),
    ]
