# Generated by Django 5.2.8 on 2025-11-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0012_order_commission_fee_order_seller_earnings"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_payment_verified",
            field=models.BooleanField(default=False),
        ),
    ]
