# Generated by Django 5.2.8 on 2025-11-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0013_order_is_payment_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Product Name"),
        ),
    ]
