# Generated by Django 5.2.8 on 2025-12-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0014_alter_crop_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crop",
            options={"verbose_name": "🌾 Crop", "verbose_name_plural": "🌾 Crops"},
        ),
        migrations.AlterModelOptions(
            name="groupbuy",
            options={
                "verbose_name": "🤝 Group Buy",
                "verbose_name_plural": "🤝 Group Buys",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "📦 Order", "verbose_name_plural": "📦 Orders"},
        ),
    ]
