# Generated by Django 5.2.8 on 2025-12-01 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0015_alter_crop_options_alter_groupbuy_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique ID for the URL (e.g., 'root-vegetables')",
                        unique=True,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🌱", help_text="Paste an emoji here", max_length=10
                    ),
                ),
            ],
            options={
                "verbose_name": "📂 Category",
                "verbose_name_plural": "📂 Categories",
            },
        ),
        migrations.AlterField(
            model_name="crop",
            name="location",
            field=models.CharField(
                default="Farm Location", help_text="e.g. Sebeta", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Product Name"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crops",
                to="marketplace.category",
            ),
        ),
    ]
