# Generated by Django 5.2.8 on 2025-12-01 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0016_category_alter_crop_location_alter_crop_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="dispatch_method",
            field=models.CharField(
                choices=[
                    ("PENDING", "Calculating..."),
                    ("DEDICATED", "Dedicated Fleet (Urban)"),
                    ("CDN", "Crowd-Delivery Network (Bulk/Long-Haul)"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="distance_km",
            field=models.IntegerField(default=5, help_text="Distance used for logic"),
        ),
        migrations.AddField(
            model_name="order",
            name="weight_kg",
            field=models.IntegerField(
                default=10, help_text="Total weight used for logic"
            ),
        ),
        migrations.CreateModel(
            name="DriverTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_city", models.CharField(max_length=100)),
                ("destination_city", models.CharField(max_length=100)),
                ("available_capacity_kg", models.IntegerField()),
                ("departure_date", models.DateTimeField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
