# Generated by Django 5.2.8 on 2025-12-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0017_order_dispatch_method_order_distance_km_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_pin",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
