# Generated by Django 5.2.8 on 2025-12-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0018_order_delivery_pin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drivertrip",
            options={
                "verbose_name": "🚚 Driver Trip",
                "verbose_name_plural": "🚚 Driver Trips",
            },
        ),
        migrations.AlterModelOptions(
            name="inputproduct",
            options={
                "verbose_name": "🚜 Input Product",
                "verbose_name_plural": "🚜 Input Products",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="pod_code",
            field=models.CharField(
                blank=True, help_text="Proof of Delivery Code", max_length=10, null=True
            ),
        ),
    ]
